name: John Un
favicon: null
layout_spectrum: 0.8651374431792647
typography_spectrum: 0.3322546468116343
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6130713843740523
  lightness: 0.7007269621826708
  saturation: 0.04408560530282557
  rhythmicContrast: 0.0028218328952789307
purpose: []
