name: John Un
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.04408560530282557
  brandStrength: 0.4957035
  lightness: 0.7007269621826708
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#565656'
    - '#919191'
    - '#AFAFAF'
  rhythmicContrast: 0.002821832895278931
typography_spectrum: 0.6353384
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
layout_spectrum: 1
